### PR TITLE
Removing unnecessary "length > 0" checks.

### PR DESCRIPTION
**Pull request by nhosoi**
Replacing selectattr with json_query in __rsyslog_version retrieval.

### CODE REVIEW

File: .travis.yml [hunk 1]
```diff
@@ -14,6 +14,7 @@ install:
   # workaround until https://github.com/ansible/molecule/issues/1727 is fixed
   - pip uninstall -y testinfra
   - pip install testinfra
+  - pip install jmespath
```
Comment (richm) [inline .travis.yml]: is there an rpm based package that provides this functionality?  We can't use pip installed packages in our products.

Comment (nhosoi) [reply .travis.yml]: This "pip install jmespath" addition is just to make the travis CI test back to work.  The other CI tests are just fine (except rhel/centos-6 :) without it.  Should we still not use pip in .travis.yml?  I'm not sure how the CI test hosts are configured, but it looks to me jmespath is missing only in the host for the travis CI and it is available in the other test hosts...  Which is the valid initial status?

In terms of  the rpm packages, there are 2 of them:
```
python2-jmespath.noarch : JSON Matching Expressions
python3-jmespath.noarch : JSON Matching Expressions
```

Comment (pcahyna) [reply .travis.yml]: @richm yes, there is a jmespath package and the rhel-system-roles package requires it in order to work - it is properly expressed as an RPM dependency. This is not related to Travis though - it does not even use a RPM distribution.

File: roles/rsyslog/roles/output_roles/files/defaults/main.yaml [hunk 2]
```diff
@@ -39,7 +39,7 @@ __rsyslog_conf_files_output_rules:
     sections:
 
       - options: |-
-          {% if rsyslog_files_actions is defined and rsyslog_files_actions | length > 0 %}
+          {% if rsyslog_files_actions is defined and rsyslog_files_actions %}
```
Comment (pcahyna) [inline roles/rsyslog/roles/output_roles/files/defaults/main.yaml]: would
```
rsyslog_files_actions | d([])
```
work? @richm what do you think?

File: roles/rsyslog/tasks/main.yaml [hunk 3]
```diff
@@ -13,7 +13,7 @@
   set_fact:
     __rsyslog_version: >-
       {{ ansible_facts.packages['rsyslog'][0].version
-      if ansible_facts.packages | selectattr('rsyslog', 'defined') | list | length > 0
+      if ansible_facts.packages | json_query('rsyslog')
```
[the remark this answers is not in the document]
Comment (nhosoi) [reply roles/rsyslog/tasks/main.yaml]: > is there a test for the problem being fixed here? I am surprised that the problem was not caught before merging #87

I will add a test case.

File: roles/rsyslog/roles/output_roles/files/defaults/main.yaml (hunk 2 above)
Comment (nhosoi) [reply roles/rsyslog/roles/output_roles/files/defaults/main.yaml]: Fixed.   I also fixed similar codes in roles/rsyslog/tasks/main.yml.

File: tests/tests_enabled.yml [hunk 4]
```diff
@@ -20,3 +20,7 @@
     - name: Check file counts in rsyslog.d
       assert:
         that: rsyslog_d_file_count.matched < 3
+
+    - name: Check __rsyslog_version is set
+      assert:
+        that: __rsyslog_version != "0.0.0"
```
Comment (pcahyna) [inline tests/tests_enabled.yml]: what does this change have in common with the rest of the commit?

File: roles/rsyslog/tasks/main.yaml (hunk 3 above)
[the remark this answers is not in the document]
Comment (pcahyna) [reply roles/rsyslog/tasks/main.yaml]: It does not seem like a good way to test this. It is an internal variable; what if it gets renamed or its scope restricted? This way you are basically relying on the unfortunate fact that variables leak out from the role. Can't you rather test for the actual functionality that needs this variable? I mean, before you fixed the problem, the role must have behaved differently in some situation, otherwise the whole code would be useless.

File: tests/tests_enabled.yml (hunk 4 above)
Comment (nhosoi) [reply tests/tests_enabled.yml]: > what does this change have in common with the rest of the commit?

Note: This change is a fix for "is there a test for the problem being fixed here? I am surprised that the problem was not caught before merging #87".  And the discussion is on-going in the thread https://github.com/linux-system-roles/logging/pull/91#discussion_r389896570.

File: roles/rsyslog/tasks/main.yaml (hunk 3 above)
[the remark this answers is not in the document]
Comment (nhosoi) [reply roles/rsyslog/tasks/main.yaml]: @pcahyna, currently, the version info is used only when rsyslog_in_image is true, which is not supported in the test-harness, I'd think.  Do you have any recommendation to do in such a case?  As you described above, the assertion to check `__rsyslog_version != "0.0.0"` is not ideal, but probably we could detect an error if some mismatch was introduced in a new pull request?

**Comment by nhosoi** [comment]
@pcahyna, BTW, there are 2 commits in this pr for now.  Do we want to make more smaller commits from them or is it ok with 2 commits?  (Or do we want to open another pr with a part of them?)

https://github.com/linux-system-roles/logging/pull/91/commits
[1]
```
Removing unnecessary "length > 0" checks.
Replacing selectattr with json_query in __rsyslog_version retrieval.
pip install jmespath in .travis.yml to use json_query.
```
[2]
```
Simplifying jinja2 conditional expression:
      old> variable is defined and variable != []
      new> variable | d([])
Adding a test case to check __rsyslog_version is set properly.
```

File: tests/tests_enabled.yml (hunk 4 above)
Comment (pcahyna) [reply tests/tests_enabled.yml]: I know, but what does this new test have in common with removing length filters from `rsyslog_files_actions` etc ? I.e. why to have a commit
```
 Simplifying jinja2 conditional expression:

  old> variable is defined and variable != []
  new> variable | d([])

Adding a test case to check __rsyslog_version is set properly.
```
when the "Adding a test case to check __rsyslog_version is set properly." part has nothing to do with the "Simplifying jinja2 conditional expression:" part? Please split the commit in two. (You can keep both in this PR.)

**Comment by pcahyna** [comment]
@nhosoi I would prefer to split [2] in two smaller commits and I don't think a separate PR is justified at this time.

File: tests/tests_enabled.yml (hunk 4 above)
Comment (nhosoi) [reply tests/tests_enabled.yml]: Understood your question.  This change was made before the agreement made in the meeting.  Instead of fixing the issues raised in the review process in the same pr, I will open a new pr for them.  Actually, that was my question https://github.com/linux-system-roles/logging/pull/91#issuecomment-597248067 :)

**Comment by nhosoi** [comment]
> @nhosoi I would prefer to split [2] in two smaller commits and I don't think a separate PR is justified at this time.

Thanks, @pcahyna.  I dropped the test case change.

File: tests/tests_enabled.yml (hunk 4 above)
Comment (pcahyna) [reply tests/tests_enabled.yml]: But the issue of not having a test for the change in this PR is related to this PR, so please add it to this PR. How would you test that the change is correct otherwise?

File: roles/rsyslog/tasks/main.yaml (hunk 3 above)
[the remark this answers is not in the document]
Comment (pcahyna) [reply roles/rsyslog/tasks/main.yaml]: Ah. So there is even a test missing for `rsyslog_in_image`, so there is a bigger problem.

File: tests/tests_enabled.yml (hunk 4 above)
Comment (pcahyna) [reply tests/tests_enabled.yml]: We need to reach an agreement first on what is actually a good test, though.

File: tests/tests_enabled.yml [hunk 5]
```diff
@@ -20,3 +20,16 @@
...
         that: rsyslog_d_file_count.matched < 3
+
+    - name: Get rsyslog_version_str
+      command: /bin/grep "^# rsyslog version is " /etc/rsyslog.conf
+      register: rsyslog_version_str
+      changed_when: false
+
+    - name: Retrieve rsyslog_Version
+      set_fact:
+        rsyslog_version: "{{ rsyslog_version_str.stdout | regex_search('[0-9]*\\.[0-9]*\\.[0-9]*') }}"
```
Comment (pcahyna) [inline tests/tests_enabled.yml]: Why do you need to set a fact? Can't you just set a variable on the task which needs it, i.e. the task below?

Comment (pcahyna) [reply tests/tests_enabled.yml]: Note: it is of course not extremely important to have this done properly in a test playbook, but I would still prefer it to set a good example.

Comment (richm) [reply tests/tests_enabled.yml]: > set a variable on the task which needs it, i.e. the task below?

Not sure what you mean

Comment (pcahyna) [reply tests/tests_enabled.yml]:
```yaml
    - name: Check rsyslog_version
      assert:
        that: rsyslog_version | d() and rsyslog_version != "0.0.0"
      vars:
        rsyslog_version: "{{ rsyslog_version_str.stdout | regex_search('[0-9]*\\.[0-9]*\\.[0-9]*') }}"
```

Comment (richm) [reply tests/tests_enabled.yml]: cool - I didn't know about that feature

Comment (nhosoi) [reply tests/tests_enabled.yml]: Thank you, @pcahyna and @richm.  I pushed the fix following the suggestion by Pavel.

**Comment by pcahyna** [comment]
I propose to merge this with squashing the last two commits together. But I don't like the way how the version determination is tested and that the version is being added to the configuration file just to make the change testable. I hope it will be possible to improve the test.

**Comment by nhosoi** [comment]
> I propose to merge this with squashing the last two commits together. But I don't like the way how the version determination is tested and that the version is being added to the configuration file just to make the change testable. I hope it will be possible to improve the test.

Indeed, I added the version string to the main rsyslog config file for checking it in the test.  But I'm now thinking it might be somehow more useful than I first thought...  The rsyslog version is the one when the logging role is executed.  Do we care the situation for the administrator to run "yum update" on the target hosts and the version of the system (rsyslog in this case) is more advanced than the one for the configuration?  I'd think the backward compatibility is pretty much guaranteed, so any sudden stop-working event won't occur.  But, getting deprecated warning level event might start at some point.  At that time, we may find the information useful for troubleshooting...

**Comment by pcahyna** [comment]
> Putting my comment aside, shall I open an issue for "the version is being added to the configuration file" just for testing not to forget?

Yes please. Note though that it is not just about the version added to the configuration file. The problem is in general that it is not a functional test, i.e. it does not test that the functionality for which you need the version test is working properly.

By the way, does your test fail in the version before your fix?

**Comment by nhosoi** [comment]
> Yes please.

All right.  Will do.

> Note though that it is not just about the version added to the configuration file. The problem is in general that it is not a functional test, i.e. it does not test that the functionality for which you need the version test is working properly.

In this case, the issue is lacking the test platform which pulls rsyslog from the container image.  (note: in the logging role code, it is in the rsyslog_in_image block.)  The part of the logging role was planed to use in the openshift logging and tested and verified it worked when it was implemented.  But rsyslog was dropped from the openshift logging.  Plus, the LSR logging role did not get used even before the drop.

> By the way, does your test fail in the version before your fix?

It was working in the version tagged with 0.1.0.  But I did not have a chance to test the code with rsyslog_in_image enabled after the fix -- instead of using yum, using package to install `rsyslog`, then the version info needed to be retrieved independently -- was made.

**Comment by nhosoi** [comment]
Thank you for reviewing the pr, @pcahyna.

Merging...
